version: "3.1"
services:
  music_api:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - music_network
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - RESET_DB=${RESET_DB}

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - music_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - music_network

volumes:
  ? postgres-data

networks:
  music_network:
    driver: bridge
